services:
  - type: web
    name: roadguard-backend
    env: python
    region: singapore
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --chdir backend app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9.18
